# Base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy proxy layer code
COPY . .

# Install dependencies
RUN apt-get update && \
    apt-get install -y curl && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Expose application port
EXPOSE 8001

# Command to run the proxy layer
CMD ["uvicorn", "proxy:app", "--host", "0.0.0.0", "--port", "8001"]
