# Base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy proxy layer code
COPY . .

# Install curl and dependencies for Python packages
RUN apt-get update && \
    apt-get install -y curl && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Expose application port
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
